const $ = (id) => document.getElementById(id);
const state = { execution: { page: 1, size: 50, before: null, history: [], next: null, total: 0 }, tasks: { page: 1, size: 30, items: null }, today: { page: 1, size: 20, items: [] }, calendar: { page: 1, size: 20, items: [], issues: new Map(), day: null }, services: { page: 1, size: 20, items: null }, sourceDependency: { page: 1, size: 20, view: null }, initId: null };
const labels = {queued:"排队",running:"运行",retrying:"重试",validating:"校验",publishing:"发布",success:"成功",attention:"需处理",historical_attention:"历史失败",superseded:"已被后续成功替代",cancelled:"已取消",not_dispatched:"未派发",not_due:"尚未到调度或发布时间",not_expected:"非交易日无需执行",complete:"完整",empty_verified:"已验证为空",gaps:"缺失",partial:"不完整",indeterminate:"待确认",ready:"严格就绪",ready_after_repair:"补采恢复",active:"进行中",waiting_upstream:"等待上游",operator_action_required:"需要处理",present:"审计通过",observed_only:"已有数据",missing:"缺失",pending:"待核验",acquisition:"原生采集",transformation:"派生计算",draft:"草稿",retired:"已停用"};
const fmt = (v) => Number(v || 0).toLocaleString();
const esc = (v) => String(v ?? "—").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pill = (v) => `<span class="pill ${esc(v)}">${esc(labels[v] || v)}</span>`;
const isoDate = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const monthValue = (d=new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;

async function api(path, options={}) {
  const response = await fetch(path, options);
  if (!response.ok) {
    let message = `HTTP ${response.status}`;
    try { const body = await response.json(); message = body.error?.message || body.detail || message; } catch (_) {}
    throw new Error(message);
  }
  return response.json();
}
function notice(message) { $("notice").textContent=message; $("notice").classList.toggle("hidden",!message); }
function activate(name) {
  document.querySelectorAll("[data-panel]").forEach(x=>x.classList.toggle("hidden",x.dataset.panel!==name));
  document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===name));
  const names={overview:"数据运营总览",today:"今日交付",tasks:"采集任务",executions:"执行历史",calendar:"数据日历",coverage:"覆盖审计",initialization:"数据初始化",sources:"数据依赖",services:"对外服务目录",investment:"投资日历"};
  $("pageTitle").textContent=names[name];
  ({today:loadToday,tasks:loadTasks,executions:loadExecutions,calendar:loadCalendar,coverage:loadCoverage,initialization:loadInitialization,sources:loadSources,services:loadServices,investment:loadInvestment}[name]||(()=>{}))();
}

async function loadOverview() {
  const health = await api("/api/v1/ops/data-health");
  const s=health.summary;
  const readyRate=s.latest_dataset_states?Math.round(s.ready_dataset_states*1000/s.latest_dataset_states)/10:100;
  $("metricActive").textContent=fmt(s.active_task_instances); $("metricAttention").textContent=fmt(s.open_issues);
  $("metricReady").textContent=`${fmt(s.ready_dataset_states)} / ${fmt(s.latest_dataset_states)}`; $("metricMissing").textContent=`${fmt(s.missing_partitions)} / ${fmt(s.partial_partitions)}`;
  const banner=$("healthBanner"); banner.className=`health-banner ${health.status}`;
  const headline=health.status==="healthy"?"数据链路健康":s.operator_action_required?`${fmt(s.operator_action_required)} 个问题需要处理`:`数据主体可用，${fmt(s.waiting_upstream)} 个数据集等待上游`;
  $("healthKicker").textContent=health.status==="healthy"?"全部正常":s.operator_action_required?"需要处理":"自动恢复中";
  $("healthTitle").textContent=headline;
  $("healthSummary").textContent=`最新状态 ${s.ready_dataset_states}/${s.latest_dataset_states} 已就绪；当前 ${s.open_issues} 个问题，历史重试尝试 ${s.attention_attempts} 次。尝试次数不再当作问题数。`;
  $("readinessRate").textContent=`${readyRate}%`;
  $("flowExecution").textContent=s.operator_action_required?`${s.operator_action_required} 个需要处理`:s.active_task_instances?`${s.active_task_instances} 个正在运行`:"调度正常";
  $("flowExecutionHint").textContent=`当前逻辑范围；执行历史保留 ${fmt(s.attention_attempts)} 次异常尝试`;
  $("flowValidation").textContent=s.not_ready_dataset_states?`${s.not_ready_dataset_states} 个未通过`:`${s.latest_dataset_states} 个全部通过`;
  $("flowValidationHint").textContent=`缺失 ${fmt(s.missing_partitions)} · 不完整 ${fmt(s.partial_partitions)}`;
  $("flowDelivery").textContent=s.not_ready_dataset_states?"已限制未就绪数据":"服务数据已就绪";
  $("flowDeliveryHint").textContent=`${fmt(s.ready_dataset_states)} 个最新数据状态可供服务读取`;
  $("issueCount").textContent=fmt(s.open_issues);
  $("issueList").innerHTML=health.issues.length?health.issues.map(x=>{
    const ratio=x.completeness_ratio==null?"—":`${Math.round(x.completeness_ratio*1000)/10}%`;
    const quantity=x.expected_count==null?"":`<span>实体完整度 ${fmt(x.actual_count)} / ${fmt(x.expected_count)}（${ratio}）</span>`;
    const next=x.next_automatic_repair_at?`<span>下次自动复查 ${new Date(x.next_automatic_repair_at).toLocaleString("zh-CN",{hour12:false})}</span>`:"";
    const explanation=x.resolution_state==="waiting_upstream"?"最近一次采集已成功，但上游尚未发布完整截面；系统会按限定范围自动复查。":"数据校验未通过，需要检查来源执行并做范围补采。";
    return `<div class="issue ${x.severity}"><div><div class="issue-title"><strong>${esc(x.dataset)}</strong>${pill(x.resolution_state)}<span>${esc(x.observation_key)}</span></div><div class="issue-meta"><span>${esc(explanation)}</span>${quantity}${next}</div></div><div class="issue-actions">${x.source_execution_id?`<button data-execution="${x.source_execution_id}">查看最近尝试</button>`:""}</div></div>`;
  }).join(""):'<div class="empty-state">当前没有数据缺失或完整性问题。</div>';
  $("updatedAt").textContent=`更新于 ${new Date(health.generated_at).toLocaleTimeString("zh-CN")}`;
}

function renderTodayRows(){
  const status=$("todayStatus").value,query=$("todaySearch").value.trim().toLowerCase();
  const items=state.today.items.filter(x=>(!status||x.delivery_status===status)&&(!query||[x.task_key,...(x.output_datasets||[]),x.delivery_status,x.execution_status,x.current_node_key].join(" ").toLowerCase().includes(query)));
  const pages=Math.max(1,Math.ceil(items.length/state.today.size));state.today.page=Math.min(state.today.page,pages);const start=(state.today.page-1)*state.today.size,rows=items.slice(start,start+state.today.size);
  $("todayRows").innerHTML=rows.map(x=>{const displayStatus=x.not_due_reason==="non_trading_day"?"not_expected":(x.execution_status||x.status);const delivery=x.not_due_reason==="non_trading_day"?"not_expected":(x.delivery_status||"attention");const outputs=(x.output_datasets||[]).map(v=>`<span class="dataset-chip">${esc(v)}</span>`).join("");return `<tr><td><strong class="task-name">${esc(x.task_key)}</strong><small class="dataset-list"><b>产出</b>${outputs||"—"}</small></td><td>${esc(x.observation_key||$("todayDate").value)}</td><td>${pill(displayStatus)}</td><td>${esc(x.current_node_key)}</td><td>${pill(delivery)} · ${fmt(x.ready_datasets)} / ${fmt(x.datasets)}${x.problem_datasets?` · <b>${fmt(x.problem_datasets)} 异常</b>`:""}</td><td>${fmt(x.rows_written)} / ${fmt(x.rows_fetched)}</td><td>${x.task_execution_id?`<button data-execution="${x.task_execution_id}">详情</button>`:"—"}</td></tr>`;}).join("")||'<tr><td colspan="7" class="empty-row">没有匹配任务</td></tr>';
  $("todayResultCount").textContent=`${items.length} 个任务`;
  $("todayPage").textContent=`第 ${state.today.page} / ${pages} 页`;
  $("todayPrev").disabled=state.today.page===1;$("todayNext").disabled=state.today.page===pages;
}

async function loadToday() {
  const day=$("todayDate").value||isoDate(new Date());
  const view=await api(`/api/v1/ops/today?data_date=${day}`), s=view.summary;
  $("todayExpected").textContent=fmt(s.expected); $("todayReady").textContent=fmt(s.strictly_ready); $("todayActive").textContent=fmt(s.active); $("todayProblem").textContent=fmt(s.attention+s.not_dispatched);
  $("todaySummary").textContent=!view.trade_day?`${day} 为非交易日：日常交易任务不创建执行实例，因此这里为空；trade_calendar 等日历型数据可能已由此前快照覆盖，请在“数据日历”查看数据证据。系统共有 ${s.configured_daily_tasks||0} 个日频任务定义。`:`${day} 数据交付：严格就绪 ${s.strictly_ready}/${s.expected} 个已到期任务；${s.recovered||0} 个由后续补采恢复；${s.not_due||0} 个任务尚未到调度或发布时间。任务行现在同时展示其输出数据集。`;
  state.today.items=view.items;state.today.page=1;renderTodayRows();
}

function renderTaskRows(){
  const query=$("taskSearch").value.trim().toLowerCase();
  const items=(state.tasks.items||[]).filter(x=>!query||[x.task_key,...(x.input_datasets||[]),...(x.output_datasets||[])].join(" ").toLowerCase().includes(query));
  const pages=Math.max(1,Math.ceil(items.length/state.tasks.size));state.tasks.page=Math.min(state.tasks.page,pages);const start=(state.tasks.page-1)*state.tasks.size,rows=items.slice(start,start+state.tasks.size);
  const chips=v=>{const a=v||[];return a.length?`${a.slice(0,4).map(x=>`<span class="dataset-chip">${esc(x)}</span>`).join("")}${a.length>4?`<span class="dataset-more">+${a.length-4}</span>`:""}`:"<span class=\"muted\">无</span>"};
  const lifecycleLabels={active:"已启用",draft:"草稿",retired:"已停用"};
  const cadenceLabels={daily:"每日",weekly:"每周",monthly:"每月",quarterly:"每季",dependency:"依赖触发",manual:"按需"};
  $("taskRows").innerHTML=rows.map(x=>`<tr><td><strong class="task-name">${esc(x.task_key)}</strong><small><span class="pill ${esc(x.lifecycle_status)}">${esc(lifecycleLabels[x.lifecycle_status]||x.lifecycle_status)}</span></small></td><td><span class="cadence-pill">${esc(cadenceLabels[x.cadence]||x.cadence||"按需")}</span><small>${esc(x.schedule_expression||x.schedule_mode||"手动 / 依赖触发")}</small></td><td>${pill(x.workflow_kind)}<small>版本 ${x.version}</small></td><td><div class="dataset-flow"><div><b>输入</b>${chips(x.input_datasets)}</div><span>→</span><div><b>输出</b>${chips(x.output_datasets)}</div></div></td><td><strong>${fmt(x.node_count)}</strong><small>个内部节点</small></td><td><button data-task="${x.task_definition_id}">查看节点</button></td></tr>`).join("")||'<tr><td colspan="6" class="empty-row">没有匹配任务</td></tr>';
  $("taskResultCount").textContent=`筛选结果 ${items.length} 个任务`;
  $("taskPage").textContent=`第 ${state.tasks.page} / ${pages} 页 · ${items.length} 个任务`;$("taskPrev").disabled=state.tasks.page===1;$("taskNext").disabled=state.tasks.page===pages;
}
async function loadTasks(reset=false){if(reset)state.tasks={page:1,size:30,items:null};if(!state.tasks.items){const p=new URLSearchParams({limit:"200"});if($("taskCadence").value)p.set("cadence",$("taskCadence").value);if($("taskKind").value)p.set("workflow_kind",$("taskKind").value);if($("taskLifecycle").value)p.set("lifecycle_status",$("taskLifecycle").value);const view=await api(`/api/v1/ops/tasks?${p}`);state.tasks.items=view.items;}renderTaskRows();}

async function loadExecutions(reset=false) {
  if(reset) state.execution={page:1,size:50,before:null,history:[],next:null,total:0};
  const p=new URLSearchParams({limit:String(state.execution.size)}); if(state.execution.before)p.set("before_id",state.execution.before); if($("executionStatus").value)p.set("status",$("executionStatus").value); if($("executionTask").value.trim())p.set("task_key",$("executionTask").value.trim());
  const view=await api(`/api/v1/ops/executions?${p}`); state.execution.next=view.page.next_cursor;state.execution.total=Number(view.page.total||0);
  $("executionRows").innerHTML=view.items.map(x=>{const r=x.resolution||{},displayStatus=x.status==="attention"&&x.is_current_scope_execution===false?"historical_attention":r.resolution_state||x.status,latest=r.latest_execution_id?`<button data-execution="${r.latest_execution_id}">最新实例</button>`:"",definition=r.action==="fix_definition"?`<button data-task="${x.task_definition_id}">查看任务</button>`:"";return `<tr><td>#${x.task_execution_id}</td><td><strong>${esc(x.task_key)}</strong><small>版本 ${x.definition_version}</small></td><td>${esc(x.purpose)}</td><td>${esc(x.observation_key)}<small>${esc(x.observation_start)} → ${esc(x.observation_end)}</small></td><td>${pill(displayStatus)}<small>${esc(x.current_node_key)}</small></td><td>${fmt(x.attempt_count)}/${fmt(x.max_attempts)}</td><td>${fmt(x.rows_fetched)} / ${fmt(x.rows_written)}</td><td><strong>${esc(r.action==="wait_upstream"?"系统自动复查":x.final_error_category||"—")}</strong><small>${esc(r.guidance||"查看运行详情")}</small></td><td class="row-actions"><button data-execution="${x.task_execution_id}">详情</button>${latest}${definition}${r.retryable?`<button class="danger" data-retry="${x.task_execution_id}" data-task-key="${esc(x.task_key)}">重试</button>`:""}</td></tr>`}).join("")||'<tr><td colspan="9">没有匹配实例</td></tr>';
  const start=state.execution.total?((state.execution.page-1)*state.execution.size)+1:0,end=Math.min(state.execution.page*state.execution.size,state.execution.total);
  $("executionPage").textContent=`第 ${state.execution.page} 页 · ${fmt(start)}–${fmt(end)} / 共 ${fmt(state.execution.total)} 条`; $("executionPrev").disabled=state.execution.page===1; $("executionNext").disabled=!state.execution.next;
}
async function showExecution(id){const view=await api(`/api/v1/ops/executions/${id}`),x=view.execution,r=x.resolution||{};$("detailTitle").textContent=`执行实例 #${id}`;const eventLabels={"node.condition.completed":"执行条件已确认","node.scope_plan.completed":"采集范围已确定","node.acquire.started":"开始采集","node.acquire.request_completed":"上游请求已完成","node.acquire.completed":"数据采集已完成","node.validate.completed":"数据校验已完成","dataset.validation.completed":"完整性证据已保存","dataset.state.updated":"数据状态已发布"};const events=(view.events||[]).map(e=>`<li><b>${esc(eventLabels[e.event_type]||e.event_type)}</b><span>${esc(e.node_key||"")} · ${new Date(e.occurred_at).toLocaleString("zh-CN",{hour12:false})}</span></li>`).join("");const nodeOrder=["condition","scope_plan","acquire","transform","validate","publish"],nodes=Object.entries(x.node_status||{}).sort((a,b)=>nodeOrder.indexOf(a[0])-nodeOrder.indexOf(b[0])).map(([key,value],i)=>`<article><span>${i+1}</span><div><strong>${esc(key)}</strong><small>${pill(value)}</small></div></article>`).join("");const issueTitle=r.action==="wait_upstream"?"为何正在等待":"为什么需要处理",status=r.resolution_state||x.status,definition=r.action==="fix_definition"?`<button data-task="${x.task_definition_id}">查看任务定义与节点</button>`:"";$("detailBody").innerHTML=`<div class="detail-grid"><article><small>任务</small><strong>${esc(x.task_key)} · 版本 ${x.definition_version}</strong></article><article><small>业务数据周期</small><strong>${esc(x.observation_start)} → ${esc(x.observation_end)}</strong></article><article><small>状态 / 当前节点</small><strong>${pill(status)} ${esc(x.current_node_key)}</strong></article><article><small>尝试</small><strong>${fmt(x.attempt_count)} / ${fmt(x.max_attempts)}</strong></article></div>${x.status==="attention"?`<div class="resolution"><strong>${issueTitle}</strong><p>${esc(x.final_error_message||x.final_error_category||"未记录明确错误")}</p><strong>下一步</strong><p>${esc(r.guidance)}</p>${definition}${r.retryable?`<button class="primary" data-retry="${id}" data-task-key="${esc(x.task_key)}">确认重试此实例</button>`:""}</div>`:""}<h3>本次执行节点</h3><div class="node-flow compact-flow">${nodes||"暂无节点状态"}</div><h3>证据时间线</h3><ol class="event-list">${events||"<li>暂无事件</li>"}</ol>`;$("detailDialog").showModal();}
async function showTask(id){const view=await api(`/api/v1/ops/tasks/${id}`),t=view.task,d=t.definition||{},nodes=d.nodes||[],lifecycle={active:"已启用",draft:"草稿",retired:"已停用"};$("detailTitle").textContent=`采集任务 · ${t.task_key}`;$("detailBody").innerHTML=`<div class="detail-grid"><article><small>类型 / 版本</small><strong>${esc(labels[t.workflow_kind]||t.workflow_kind)} · ${t.version}</strong></article><article><small>生命周期</small><strong>${esc(lifecycle[t.lifecycle_status]||t.lifecycle_status)}</strong></article><article><small>输入数据集</small><strong>${esc((d.input_datasets||[]).join("、")||"无")}</strong></article><article><small>输出数据集</small><strong>${esc((d.output_datasets||[]).join("、")||"无")}</strong></article></div><h3>内部节点</h3><div class="node-flow">${nodes.map((n,i)=>`<article><span>${i+1}</span><div><strong>${esc(n.key)}</strong><small>${esc(labels[n.kind]||n.kind)} · ${esc(n.handler_key)}</small><p>最多尝试 ${fmt(n.retry?.max_attempts||1)} 次</p></div></article>`).join("")||"暂无节点"}</div>`;$("detailDialog").showModal();}
async function retryExecution(id,taskKey){if(!confirm(`确认重试任务 ${taskKey||""} 的执行实例 #${id}？系统会保留原错误证据并从持久队列重新执行。`))return;await api(`/api/v1/ops/executions/${id}/retry`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"operator confirmed retry from dashboard"})});notice(`实例 #${id} 已进入重试队列。`);$("detailDialog").close();loadExecutions(true);loadOverview();}

function renderMonth(gridId, month, rows, detail) {
  const [y,m]=month.split("-").map(Number), first=new Date(y,m-1,1), last=new Date(y,m,0), offset=(first.getDay()+6)%7, byDay=new Map(rows.map(x=>[String(x.data_date||x.event_date).slice(0,10),x])); let html="";
  for(let i=0;i<offset;i++)html+='<div class="day outside"></div>';
  for(let d=1;d<=last.getDate();d++){const key=`${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`,x=byDay.get(key);let cls="none",text="暂无审计记录";if(x){if(Number(x.problems)>0){cls="problem";text=`${x.problems} 个问题 · ${x.ready||0} 通过`;}else if(Number(x.active)>0){cls="active";text=`${x.active} 进行中`;}else{cls="complete";text=`${x.ready}/${x.dataset_states} 通过`;}}html+=`<button class="day ${cls}" data-date="${key}"><b>${d}</b><small>${esc(detail?detail(x):text)}</small></button>`;}
  $(gridId).innerHTML=html;
}
async function loadCalendar(){const month=$("calendarMonth").value||monthValue(),[y,m]=month.split("-").map(Number),start=`${month}-01`,end=isoDate(new Date(y,m,0));const view=await api(`/api/v1/ops/coverage/calendar?start_date=${start}&end_date=${end}`);renderMonth("calendarGrid",month,view.days);$("calendarGrid").onclick=e=>{const b=e.target.closest("[data-date]");if(b)loadCalendarDay(b.dataset.date);};}
function renderCalendarDetail(){const status=$("calendarDetailStatus").value,query=$("calendarDetailSearch").value.trim().toLowerCase();let items=state.calendar.items.filter(x=>(!status||(status==="problem"?["missing","partial"].includes(x.status):x.status===status))&&(!query||x.dataset_name.toLowerCase().includes(query)));const pages=Math.max(1,Math.ceil(items.length/state.calendar.size));state.calendar.page=Math.min(state.calendar.page,pages);const start=(state.calendar.page-1)*state.calendar.size,rows=items.slice(start,start+state.calendar.size);$("calendarDetailRows").innerHTML=rows.map(x=>{const issue=state.calendar.issues.get(`${x.dataset_name}:${state.calendar.day}`),ratio=x.entity_coverage_ratio==null?"":` · ${Math.round(Number(x.entity_coverage_ratio)*1000)/10}%`,volume=x.expected_entity_count==null?`${fmt(x.row_count)} 行`:`${fmt(x.entity_count)} / ${fmt(x.expected_entity_count)} 实体${ratio}`;const guidance=issue?(issue.resolution_state==="waiting_upstream"?"上游尚未发布完整截面，系统将自动复查":"需要检查采集与校验证据"):(x.status==="pending"?"核验尚未完成":"无需处理");return `<tr><td><strong>${esc(x.dataset_name)}</strong></td><td>${pill(issue?.resolution_state||x.status)}</td><td>${volume}</td><td>${esc(guidance)}</td><td>${new Date(x.checked_at).toLocaleString("zh-CN",{hour12:false})}</td><td>${issue?.source_execution_id?`<button data-execution="${issue.source_execution_id}">查看采集证据</button>`:"—"}</td></tr>`;}).join("")||'<tr><td colspan="6">没有匹配的数据集</td></tr>';$("calendarDetailPage").textContent=`第 ${state.calendar.page} / ${pages} 页 · ${items.length} 个数据集`;$("calendarDetailPrev").disabled=state.calendar.page===1;$("calendarDetailNext").disabled=state.calendar.page===pages;}
async function loadCalendarDay(day){const [view,health]=await Promise.all([api(`/api/v1/ops/coverage/calendar/${day}`),api("/api/v1/ops/data-health")]),s=view.summary;state.calendar={...state.calendar,page:1,items:view.datasets,day,issues:new Map((health.issues||[]).map(x=>[`${x.dataset}:${x.observation_key}`,x]))};$("calendarDetail").classList.remove("hidden");$("calendarDetailTitle").textContent=`${day} 数据明细`;$("calendarDetailSummary").textContent=`共 ${s.datasets} 个已审计数据集：${s.ready} 个通过，${s.problems} 个缺失/不完整，${s.active} 个待核验。问题数据优先展示，状态来自数据证据而不是任务结果。`;renderCalendarDetail();$("calendarDetail").scrollIntoView({behavior:"smooth",block:"nearest"});}

async function loadCoverage(){const view=await api("/api/v1/ops/coverage");const s=view.summary;$("coverageSummary").textContent=`${s.audited}/${s.auditable} 已审计 · ${s.with_gaps} 个数据集有缺口 · 缺失 ${fmt(s.missing_partitions)} 个周期`;$("coverageRows").innerHTML=view.datasets.map(x=>{const a=x.latest||{};return `<tr><td><strong>${esc(x.dataset)}</strong></td><td>${esc(x.strategy)}</td><td>${pill(a.status||"unaudited")}</td><td>${esc(a.start_date)} → ${esc(a.end_date)}</td><td>${fmt(a.missing_partitions)}</td><td>${fmt(a.partial_partitions)}</td><td>${x.repairable?"可自动补采":"仅诊断"}</td></tr>`}).join("");}
async function auditAll(){await api("/api/v1/ops/coverage/audits",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":`dashboard-audit-${Date.now()}`},body:JSON.stringify({datasets:null,all_datasets:true,start_date:null,end_date:null})});notice("已提交全部数据集严格审计；确认的缺口会进入安全修复链路。");loadCoverage();}

async function loadInitialization(){const view=await api("/api/v1/ops/initialization");const c=view.latest;state.initId=c?.initialization_id||null;$("initializationState").innerHTML=c?`<strong>#${c.initialization_id} · ${esc(c.status)}</strong><p>阶段：${esc(c.phase_name)} · 完成 ${fmt(c.completed_steps)}/${fmt(c.planned_steps)} · 失败 ${fmt(c.failed_steps)}</p>`:"尚未运行初始化";if(!c){$("initializationRows").innerHTML="";return;}const rows=await api(`/api/v1/ops/initialization/${c.initialization_id}/steps?limit=500`);$("initializationRows").innerHTML=rows.map(x=>`<tr><td>${esc(x.resource_type)}</td><td>${esc(x.task_key||x.dataset_name)}</td><td>${esc(x.observation_key||x.start_date)} → ${esc(x.observation_end||x.end_date)}</td><td>${pill(x.status)}</td><td>${fmt(x.attempt)}/${fmt(x.max_attempts)}</td><td>${esc(x.failure_category||x.error_message||"")}</td></tr>`).join("");}
async function startInitialization(){if(!confirm("确认对全部业务数据做严格审计，并只补采确认缺失的周期？"))return;const body={profile:$("initProfile").value,history_start:$("initStart").value||null,history_end:$("initEnd").value||null,auto_activate:true};await api("/api/v1/ops/initialization",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":`dashboard-init-${body.profile}-${body.history_start}-${body.history_end}`},body:JSON.stringify(body)});notice("初始化已启动。");loadInitialization();}

async function loadSources(reset=false){
  const sources=await api("/api/v1/data/sources"),modeLabels={scheduled_pull:"定时采集",query_through:"按需查询"},marks={tushare:"TS",financial_data:"FD",chinamoney:"CM"};
  const capabilityCount=sources.items.reduce((sum,x)=>sum+Number(x.configuration?.catalog_discovered_routes||x.endpoint_count||0),0),persistCount=sources.items.filter(x=>x.license_policy?.persist_raw_records).length;
  $("sourceProviderCount").textContent=fmt(sources.total);$("sourceCapabilityCount").textContent=fmt(capabilityCount);$("sourcePersistCount").textContent=fmt(persistCount);
  $("sourceCards").innerHTML=sources.items.map(x=>{let host=x.base_url;try{host=new URL(x.base_url).hostname}catch(_){}const capabilities=Number(x.configuration?.catalog_discovered_routes||x.endpoint_count||0),policy=x.license_policy?.persist_raw_records?"允许审计落库":"仅按需透传";return `<article class="provider-card ${esc(x.source_id)}"><div class="provider-head"><span class="provider-mark">${esc(marks[x.source_id]||x.source_id.slice(0,2).toUpperCase())}</span><span class="provider-state"><i></i>已注册</span></div><h3>${esc(x.display_name)}</h3><code>${esc(x.source_id)}</code><div class="provider-capability"><strong>${fmt(capabilities)}</strong><span>项可用能力</span></div><div class="provider-meta"><div><small>接入方式</small><b>${x.acquisition_modes.map(v=>esc(modeLabels[v]||v)).join(" / ")}</b></div><div><small>数据策略</small><b>${esc(policy)}</b></div><div><small>凭据管理</small><b>${x.credential_required?"环境变量托管":"公开数据源"}</b></div><div><small>服务主机</small><b title="${esc(x.base_url)}">${esc(host)}</b></div></div></article>`;}).join("");
  if(reset){state.sourceDependency.page=1;state.sourceDependency.view=null;}
  if(!state.sourceDependency.view)state.sourceDependency.view=await api("/api/v1/data/source-priorities");const view=state.sourceDependency.view,s=view.provider_equivalence_summary;
  $("sourceRouteCount").textContent=fmt(s.tushare_direct);$("sourceRequiredCount").textContent=fmt(s.tushare_derived);$("sourceRealtimeCount").textContent=fmt(s.tushare_announcement_parse);$("sourceNoLocalCount").textContent=fmt(s.financial_data_only);
  const category=$("sourceDependencyClass").value,query=$("sourceDependencySearch").value.trim().toLowerCase();let items=view.items.filter(x=>{const p=x.provider_equivalence,apis=[...p.tushare_interfaces,...p.related_tushare_interfaces].map(y=>y.api_name);return(!category||p.equivalence_class===category)&&(!query||[x.route,...x.local_datasets,...apis].join(" ").toLowerCase().includes(query));});const pages=Math.max(1,Math.ceil(items.length/state.sourceDependency.size));state.sourceDependency.page=Math.min(state.sourceDependency.page,pages);const start=(state.sourceDependency.page-1)*state.sourceDependency.size,rows=items.slice(start,start+state.sourceDependency.size);
  const classLabels={tushare_direct:"Tushare 直接等价",tushare_derived:"Tushare 确定性派生",tushare_announcement_parse:"Tushare 公告解析",financial_data_only:"Financial Data 必需"};
  const coverageLabels={full_direct:"完整等价",full_after_deterministic_derivation:"派生后完整",full_after_evidence_backed_a_share_parsing:"解析后完整",partial_overlap_only:"仅部分重叠",no_equivalent:"没有等价能力"},preferredLabels={local_db_first:"优先本地数据库",financial_data_first:"优先 Financial Data"},adapterLabel=v=>v==="canonical_dataset_required"?"待建设规范数据集":v==="adapter_required"?"需要标准适配器":String(v||"").startsWith("partial_ready")?"本地部分就绪":v||"未标注适配状态";
  document.querySelectorAll("[data-source-class]").forEach(x=>x.classList.toggle("active",x.dataset.sourceClass===category));
  $("sourceDependencyTotal").textContent=fmt(view.items.length);$("sourceDependencyResult").textContent=`当前筛选 ${items.length} / ${view.items.length} 项能力`;
  $("sourceDependencyRows").innerHTML=rows.map(x=>{const p=x.provider_equivalence,apis=p.tushare_interfaces.length?p.tushare_interfaces:p.related_tushare_interfaces;const apiText=apis.length?apis.map(y=>`<span class="api-chip"><b>${esc(y.api_name)}</b><em class="${y.collectable?"available":"unavailable"}">${esc(y.permission)}</em></span>`).join(""):'<span class="source-empty">Financial Data 专属</span>';const local=x.local_datasets.length?`<div class="source-datasets">${x.local_datasets.map(v=>`<span>${esc(v)}</span>`).join("")}</div>`:'<span class="source-empty">暂无本地规范数据</span>';return `<tr><td><code class="route-code">${esc(x.route)}</code><small>${esc(preferredLabels[x.preferred_read]||x.preferred_read)}</small></td><td><span class="strategy-tag ${esc(p.equivalence_class)}">${esc(classLabels[p.equivalence_class]||p.equivalence_class)}</span><small>${esc(coverageLabels[p.coverage]||p.coverage)}</small></td><td>${local}<small class="adapter-label">${esc(adapterLabel(x.adapter_status))}</small></td><td><div class="api-list">${apiText}</div></td><td><p class="source-rationale">${esc(p.rationale)}</p><small class="token-state ${p.current_token_ready?"ready":"fallback"}">${p.current_token_ready?"当前 Token 可覆盖":"需要外部补充或建设本地能力"}</small></td></tr>`;}).join("")||'<tr><td colspan="5" class="empty-row">没有匹配的数据能力</td></tr>';
  $("sourceDependencyPage").textContent=`第 ${state.sourceDependency.page} / ${pages} 页 · ${items.length} 条`;$('sourceDependencyPrev').disabled=state.sourceDependency.page===1;$('sourceDependencyNext').disabled=state.sourceDependency.page===pages;
}

async function loadServices(reset=false){
  if(reset){state.services.page=1;state.services.items=null;}
  if(!state.services.items){const view=await api("/api/v1/catalog");state.services.items=view.layers.flatMap(layer=>layer.endpoints.map(endpoint=>({...endpoint,layer_id:layer.id,layer_title:layer.title})));}
  const layer=$("serviceLayer").value,query=$("serviceSearch").value.trim().toLowerCase();let items=state.services.items.filter(x=>(!layer||x.layer_id===layer)&&(!query||[x.name,x.path,...x.local_datasets,...x.upstream_sources].join(" ").toLowerCase().includes(query)));
  const pages=Math.max(1,Math.ceil(items.length/state.services.size));state.services.page=Math.min(state.services.page,pages);const start=(state.services.page-1)*state.services.size,rows=items.slice(start,start+state.services.size);
  $("serviceSummary").textContent=`共 ${items.length} 个匹配的对外 REST 入口；供应商、连接器和权限映射已从本目录移到“数据依赖”。`;
  $("serviceRows").innerHTML=rows.map(x=>{const datasets=x.local_datasets.length?`${x.local_datasets.slice(0,5).map(esc).join("、")}${x.local_datasets.length>5?` 等 ${x.local_datasets.length} 个`:""}`:`动态：${esc(x.dependency_scope)}`;return `<tr><td>${pill(x.layer_id)}<strong>${esc(x.name)}</strong></td><td><code>${esc(x.method)} ${esc(x.path)}</code></td><td>${datasets}</td><td>${esc(x.data_origin)}${x.derivation?`<small>${esc(x.derivation)}</small>`:""}</td><td>${esc(x.read_strategy)}</td></tr>`}).join("")||'<tr><td colspan="5">没有匹配服务</td></tr>';
  $("servicePage").textContent=`第 ${state.services.page} / ${pages} 页`;$('servicePrev').disabled=state.services.page===1;$('serviceNext').disabled=state.services.page===pages;
}

async function loadInvestment(){const month=$("investmentMonth").value||monthValue(),[y,m]=month.split("-").map(Number),start=`${month}-01`,end=isoDate(new Date(y,m,0));const view=await api(`/api/v1/research/investment-calendar?start_date=${start}&end_date=${end}&importance=important`);const events=view.events||view.items||[];const groups={};events.forEach(x=>(groups[String(x.event_date||x.date).slice(0,10)]??=[]).push(x));const rows=Object.entries(groups).map(([event_date,items])=>({event_date,items}));renderMonth("investmentGrid",month,rows,x=>x?`${x.items.length} 个事件`:"无重要事件");$("investmentGrid").onclick=e=>{const b=e.target.closest("[data-date]");if(!b)return;const items=groups[b.dataset.date]||[];$("investmentEvents").innerHTML=items.map(x=>`<div class="issue"><div><strong>${esc(x.event_name||x.name||x.title)}</strong><small>${esc(x.country)} · ${esc(x.event_time||x.time)} · 实际 ${esc(x.actual)}</small></div></div>`).join("")||"<p>当日无重要事件</p>";};}

async function refresh(){notice("");try{await loadOverview();const active=document.querySelector(".nav.active")?.dataset.view;if(active&&active!=="overview")await ({today:loadToday,tasks:loadTasks,executions:loadExecutions,calendar:loadCalendar,coverage:loadCoverage,initialization:loadInitialization,sources:loadSources,services:loadServices,investment:loadInvestment}[active]||(()=>{}))();}catch(e){notice(`加载失败：${e.message}`);}}

document.querySelector("nav").onclick=e=>{const b=e.target.closest("[data-view]");if(b)activate(b.dataset.view)};
document.body.onclick=e=>{const sourceClass=e.target.closest("[data-source-class]");if(sourceClass){$("sourceDependencyClass").value=$("sourceDependencyClass").value===sourceClass.dataset.sourceClass?"":sourceClass.dataset.sourceClass;loadSources(true);return;}const retry=e.target.closest("[data-retry]");if(retry){retryExecution(retry.dataset.retry,retry.dataset.taskKey);return;}const execution=e.target.closest("[data-execution]");if(execution){showExecution(execution.dataset.execution);return;}const task=e.target.closest("[data-task]");if(task){showTask(task.dataset.task);return;}const target=e.target.closest("[data-view-target]");if(target)activate(target.dataset.viewTarget);};
$("sidebarToggle").onclick=()=>{const collapsed=$("sidebar").classList.toggle("collapsed");localStorage.setItem("cq-sidebar",collapsed?"collapsed":"expanded");}; $("themeToggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("cq-theme",document.body.classList.contains("dark")?"dark":"light")};
$("refreshButton").onclick=refresh; $("todayDate").onchange=loadToday; $("todayQuery").onclick=()=>{state.today.page=1;renderTodayRows();}; $("todaySearch").onkeydown=e=>{if(e.key==="Enter"){state.today.page=1;renderTodayRows();}}; $("taskQuery").onclick=()=>loadTasks(true); $("taskSearch").onkeydown=e=>{if(e.key==="Enter"){state.tasks.page=1;renderTaskRows();}}; $("executionQuery").onclick=()=>loadExecutions(true); $("calendarMonth").onchange=loadCalendar; $("calendarDetailQuery").onclick=()=>{state.calendar.page=1;renderCalendarDetail();}; $("calendarDetailSearch").onkeydown=e=>{if(e.key==="Enter"){state.calendar.page=1;renderCalendarDetail();}}; $("auditAll").onclick=auditAll; $("initStartButton").onclick=startInitialization; $("sourceDependencyQuery").onclick=()=>loadSources(true); $("serviceQuery").onclick=()=>loadServices(true); $("investmentMonth").onchange=loadInvestment; $("detailClose").onclick=()=>$("detailDialog").close();
$("todayPrev").onclick=()=>{if(state.today.page>1){state.today.page--;renderTodayRows();}};$("todayNext").onclick=()=>{state.today.page++;renderTodayRows();};
$("executionPrev").onclick=()=>{if(state.execution.page===1)return;state.execution.before=state.execution.history.pop()||null;state.execution.page--;loadExecutions()};$("executionNext").onclick=()=>{if(!state.execution.next)return;state.execution.history.push(state.execution.before);state.execution.before=state.execution.next;state.execution.page++;loadExecutions()};
$("taskPrev").onclick=()=>{if(state.tasks.page>1){state.tasks.page--;renderTaskRows();}};$("taskNext").onclick=()=>{state.tasks.page++;renderTaskRows();};
$("calendarDetailPrev").onclick=()=>{if(state.calendar.page>1){state.calendar.page--;renderCalendarDetail();}};$("calendarDetailNext").onclick=()=>{state.calendar.page++;renderCalendarDetail();};
$("servicePrev").onclick=()=>{if(state.services.page>1){state.services.page--;loadServices();}};$("serviceNext").onclick=()=>{state.services.page++;loadServices();};
$("sourceDependencyPrev").onclick=()=>{if(state.sourceDependency.page>1){state.sourceDependency.page--;loadSources();}};$("sourceDependencyNext").onclick=()=>{state.sourceDependency.page++;loadSources();};
$("todayDate").value=isoDate(new Date());$("calendarMonth").value=monthValue();$("investmentMonth").value=monthValue();$("initEnd").value=isoDate(new Date(Date.now()-86400000));if(localStorage.getItem("cq-theme")==="dark")document.body.classList.add("dark");if(localStorage.getItem("cq-sidebar")==="collapsed")$("sidebar").classList.add("collapsed");refresh();setInterval(refresh,30000);
