#!/bin/sh

set -eu

backup_dir="${BACKUP_DIR:-/backups}"
interval_seconds="${BACKUP_INTERVAL_SECONDS:-86400}"
retention_days="${BACKUP_RETENTION_DAYS:-14}"
retention_count="${BACKUP_RETENTION_COUNT:-3}"
exclude_table_data="${BACKUP_EXCLUDE_TABLE_DATA:-tushare_raw_record}"
compression="${BACKUP_COMPRESSION:-zstd:1}"
last_success="${backup_dir}/.last-success"

mkdir -p "${backup_dir}"

prune_backups() {
    backup_count=0
    # Backup file names are generated by this script and contain no spaces.
    for backup_file in $(find "${backup_dir}" -maxdepth 1 -type f \
        -name 'claw-quant-*.dump' -print | sort -r); do
        backup_count=$((backup_count + 1))
        if [ "${backup_count}" -gt "${retention_count}" ]; then
            rm -f "${backup_file}" "${backup_file}.sha256"
        elif [ "${backup_count}" -gt 1 ] && find "${backup_file}" \
            -mtime "+${retention_days}" -print -quit | grep -q .; then
            # Never remove the newest completed snapshot merely because a
            # host was offline longer than the retention window.
            rm -f "${backup_file}" "${backup_file}.sha256"
        fi
    done
}

write_heartbeat() {
    heartbeat_success=0
    if [ -s "${last_success}" ]; then
        heartbeat_success="$(cat "${last_success}")"
    fi
    backup_instance="$(hostname | tr -cd 'A-Za-z0-9_.-')"
    psql -v ON_ERROR_STOP=1 \
        -c "INSERT INTO sys_service_heartbeat(
                component,instance_id,process_id,last_seen_at,details
            ) VALUES (
                'backup', '${backup_instance}', $$, NOW(),
                jsonb_build_object(
                    'backup_dir','/backups',
                    'last_success_epoch',${heartbeat_success},
                    'interval_seconds',${interval_seconds},
                    'retention_days',${retention_days},
                    'retention_count',${retention_count},
                    'excluded_table_data','${exclude_table_data}',
                    'compression','${compression}',
                    'operation',${1:-'idle'}
                )
            ) ON CONFLICT(component,instance_id) DO UPDATE SET
                process_id=EXCLUDED.process_id,
                last_seen_at=EXCLUDED.last_seen_at,
                details=EXCLUDED.details" >/dev/null || true
}

# Preserve the install/upgrade backup as the first valid daily snapshot rather
# than creating a second large dump immediately when the sidecar is introduced.
if [ ! -s "${last_success}" ] && find "${backup_dir}" -maxdepth 1 \
    -name 'claw-quant-*.dump' -mmin -1440 -print -quit | grep -q .; then
    date +%s > "${last_success}"
fi

while true; do
    now="$(date +%s)"
    previous=0
    if [ -s "${last_success}" ]; then
        previous="$(cat "${last_success}")"
    fi
    if [ $((now - previous)) -ge "${interval_seconds}" ]; then
        # Bound disk use before starting another dump. At least the newest
        # retention_count completed snapshots remain recoverable.
        prune_backups
        stamp="$(date +%Y%m%d-%H%M%S)"
        target="${backup_dir}/claw-quant-${stamp}.dump"
        partial="${target}.partial"
        rm -f "${partial}"
        pg_dump --format=custom --no-owner --no-acl \
            --compress="${compression}" \
            --exclude-table-data="${exclude_table_data}" \
            --file="${partial}" "${PGDATABASE}" &
        dump_pid=$!
        while kill -0 "${dump_pid}" 2>/dev/null; do
            write_heartbeat "'dumping'"
            sleep 30
        done
        if wait "${dump_pid}" && [ -s "${partial}" ] \
            && pg_restore --list "${partial}" >/dev/null; then
            mv "${partial}" "${target}"
            (
                cd "${backup_dir}"
                sha256sum "$(basename "${target}")" \
                    > "$(basename "${target}").sha256.partial"
                mv "$(basename "${target}").sha256.partial" \
                    "$(basename "${target}").sha256"
            )
            date +%s > "${last_success}"
            prune_backups
            printf 'backup completed: %s\n' "${target}"
        else
            rm -f "${partial}"
            printf 'backup failed at %s\n' "$(date -Iseconds)" >&2
        fi
    fi
    write_heartbeat "'idle'"
    sleep 60
done
